language: java
sudo: required
dist: trusty

jdk:
  - openjdk8
  - oraclejdk8

branches:
  except:
    - /^v|d\d+\.\d+\.\d+$/

install:
  - mvn clean install

script:
  - cat target/test-results/index.html
