name: Run regression tests for wcag

on:
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Sleep
        run: sleep 10m
      - name: Set up
        run: mvn -B -DskipTests=true clean package --file pom.xml
      - name: Run wcag regression tests
        run: java -cp "/home/runner/work/veraPDF-integration-tests/veraPDF-integration-tests/veraPDF-wcag-regression-tests/target"/'*' org.verapdf.wcag.regression.tests.RegressionTestUtils
